name=input()
mobilenum=int(input())
product_1=input("enter product_1")
price_1=float(input("enter price_1"))
product_2=input("enter product_2")
price_2=float(input("enter price_2"))
product_3=input("enter product_")
price_3=float(input("enter price_3"))
print(f"{name} your Bill")
print(f"{product_1}: ${price_1}")
print(f"{product_2}: ${price_2}")
print(f"{product_3}: ${price_3}")
total=price_1+price_2+price_3
print("Total:",total)
