product_name = input("Enter the product name: ")
stock = int(input("Enter the stock: "))
price = float(input("Enter the price: "))
ram= eval(input("Enter the avai sizes: "))
reviews=eval(input("Enter the reviews: "))
payment_mode=eval(input("Enter the payment modes: "))
brand = eval(input("Enter the brand details: "))

print(f"Product Name: {product_name}")
print(f"Stock: {stock}")
print(f"Price: ${price}")
print(f"RAM: {ram}")
print(f"Reviews: {reviews}")
print(f"Payment Mode Options: {payment_mode}")
print(f"Brand details: {brand}")
